### ISSUE TITLE
TF Question

### ISSUE THREAD

**Issue by ZhangLiang-Cencen** [Rick0514/SimpleSLAM#1]
Thanks for your good work!

Could you please tell me about the coordinate transformation between **wheel odom and lidiar odom**?

**Comment by Rick0514** [comment]
> Thanks for your good work!
> 
> Could you please tell me about the coordinate transformation between **wheel odom and lidiar odom**?

Sorry for delayed reply! In master branch, wheel odom is adjusted all the time, it's not fixed. While lidar odom is the first frame of the first scan.

**Comment by ZhangLiang-Cencen** [comment]
Thanks for your reply! 

Do they need to be in the same coordinate system when performing fusion calculations?

I mean how should other odometry coordinates be transformed into the final output odometry coordinates? For example, if wheel odometry is in the body coordinate system, how should it be corresponded to the laser odometry coordinate system during the optimization and solving process?

**Comment by Rick0514** [comment]
> Thanks for your reply!
> 
> Do they need to be in the same coordinate system when performing fusion calculations?
> 
> I mean how should other odometry coordinates be transformed into the final output odometry coordinates? For example, if wheel odometry is in the body coordinate system, how should it be corresponded to the laser odometry coordinate system during the optimization and solving process?

The slam is lidar centric, which means the global coordinate is lidar coordinate(or map frame). Wheel frame is not important because the increment value is used in optimization. Speaking of your issue, we obtained 'odom to map' transformation to relate odom frame to map frame. For more detailed, you can email me or wechat for more timely advise.

**Comment by ZhangLiang-Cencen** [comment]
Thanks! I will send you an email．
